version: '3'
services:
    jenkins:
      build:
        context: ./
        dockerfile: ./Dockerfile
      container_name: jenkins
      ports:
        - '9090:8080'
      image: jenkins
      volumes:
        - './jenkins_home:/var/jenkins_home'
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/usr/local/bin/docker:/usr/bin/docker'
